version: '3'

services:
  postgres:
    build: ./postgres
    container_name: phoenix-database
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - phoenix-data:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    restart: always

volumes:
  phoenix-data:
    driver: local
